runtime: python311
service: default

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  
handlers:
  - url: /(.*\.(css|js|png|jpg|jpeg|svg|webp|ico|txt|json|woff|woff2))$
    static_files: dist/\1
    upload: dist/.*\.(css|js|png|jpg|jpeg|svg|webp|ico|txt|json|woff|woff2)$
    http_headers:
      Cache-Control: "public, max-age=31536000, immutable"

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
