-- Raise the "Our Wall" length caps: post body 2,000 → 6,000, reply 1,000 → 3,000.
-- Long-form sharing (and now Markdown formatting, which adds syntax characters)
-- was hitting the old ceilings. Frontend (WallPostComposer/WallPostThread) and
-- backend validators (routes/wall.js) move in lockstep with these constraints.

-- Post body: the live constraint is wall_posts_content_len_check, set to <= 2000
-- in migration 078 (which superseded the original inline 028 check). Re-add at 6000.
ALTER TABLE wall_posts DROP CONSTRAINT IF EXISTS wall_posts_content_len_check;
ALTER TABLE wall_posts
  ADD CONSTRAINT wall_posts_content_len_check CHECK (char_length(content) <= 6000);

-- Reply body: the constraint came from the inline column CHECK in migration 028
-- (BETWEEN 1 AND 1000), whose name was auto-generated by Postgres. Drop it by
-- discovering the actual constraint name rather than guessing, then re-add a
-- stably named one at 3000.
DO $$
DECLARE
  con_name text;
BEGIN
  SELECT conname INTO con_name
  FROM pg_constraint
  WHERE conrelid = 'wall_post_replies'::regclass
    AND contype = 'c'
    AND pg_get_constraintdef(oid) ILIKE '%char_length(content)%';

  IF con_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE wall_post_replies DROP CONSTRAINT %I', con_name);
  END IF;
END $$;

ALTER TABLE wall_post_replies
  ADD CONSTRAINT wall_post_replies_content_len_check
  CHECK (char_length(content) BETWEEN 1 AND 3000);
